# Generated by Django 6.0.5 on 2026-05-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=300)),
                ("pub_date", models.DateField()),
            ],
        ),
    ]
