# Generated by Django 6.0.5 on 2026-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="product_id",
        ),
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="products",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(default="", upload_to="shop/images"),
        ),
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="products",
            name="sub_category",
            field=models.CharField(default="", max_length=50),
        ),
    ]
